export enum BookingStatus {
  SEARCHING_PARTNER = "SEARCHING_PARTNER",
  CONFIRMED = "CONFIRMED",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",
}
